Repository brianlong/www.validators.app, pull requests merged in 2021-12, with the labels that each got.

#279 180359150 tweak stake pool display
  .rubocop.yml
  app/assets/images/loading.gif
  app/assets/stylesheets/application.scss
  app/assets/stylesheets/buttons.scss
  app/assets/stylesheets/forms.scss
  app/assets/stylesheets/pagination.scss
  app/controllers/opt_out_requests_controller.rb
  app/helpers/sol_prices_helper.rb
  app/javascript/packs/commission_histories/index_template.vue
  app/javascript/packs/stake_accounts/index_template.vue
  app/javascript/packs/stake_accounts/stake_account_row.js
  app/views/asns/show.html.erb
  app/views/data_centers/data_center.html.erb
  app/views/opt_out_requests/index.html.erb
  app/views/sol_prices/index.html.erb
  app/views/validators/_banner.html.erb
  app/views/validators/_software_versions.html.erb
  app/views/validators/index.html.erb
  config/webpacker.yml
Labels: ready to merge

#267 180143125-cache-cluster-stats
  app/controllers/cluster_stats_controller.rb
  app/logic/report_logic.rb
  app/views/validators/_software_versions.html.erb
  app/workers/report_cluster_stats_worker.rb
  daemons/validator_score_mainnet_v1_daemon.rb
  daemons/validator_score_testnet_v1_daemon.rb
  dev/report_software_version_demo.rb
  script/prune_database_tables.rb
  test/controllers/cluster_stats_controller_test.rb
Labels: ready to merge

#283 180553625-60-days-data-retention
  script/prune_database_tables.rb
Labels: ready to merge

#276 180409120_filter_by_private_validators
  app/controllers/asns_controller.rb
  app/controllers/data_centers_controller.rb
  app/helpers/data_centers_helper.rb
  app/models/validator_score_v1.rb
  app/views/asns/show.html.erb
  app/views/data_centers/_asn_list.html.erb
  app/views/data_centers/_data_center_list.html.erb
  app/views/data_centers/data_center.html.erb
  test/models/validator_score_v1_test.rb
Labels: WIP, ready to review

#278 180458988_add_stake_pools_fees
  app/logic/stake_logic.rb
  app/models/stake_pool.rb
  db/migrate/20211129160614_add_manager_fee_to_stake_pools.rb
  db/migrate/20211130140342_add_average_validators_fee_to_stake_pools.rb
  db/schema.rb
  lib/tasks/add_stake_pools.rake
  script/gather_stake_accounts.rb
  test/logic/stake_logic_test.rb
Labels: ready to review

#282 180494618_fix_type_error
  app/javascript/src/sol_prices_charts.js
Labels: ready to merge

#286 180560658 update faq
  app/javascript/packs/commission_histories/index_template.vue
  app/views/public/commission_histories.html.erb
  app/views/public/faq.en.html.erb
Labels: ready to review

#287 180571019_add_task_to_capistrano
  config/deploy.rb
Labels: ready to merge

#292 180619231_temp_fix
  .github/workflows/test_suite.yml
Labels: ready to review

#288 180570785_change_price_format
  app/controllers/api/v1/base_controller.rb
  app/helpers/application_helper.rb
  app/javascript/packs/stake_accounts/stake_account_row.js
  app/views/api/v1/stake_accounts/_stake_account_detail.json.jbuilder
  app/views/api/v1/stake_accounts/index.json.jbuilder
  test/controllers/api/v1/stake_accounts_controller_test.rb
  test/helpers/application_helper_test.rb
  test/models/stake_account_test.rb
Labels: ready to review

#285 180555031_review_main_page_queries
  app/controllers/public_controller.rb
  app/controllers/validators_controller.rb
  app/models/validator.rb
  app/models/validator_score_v1.rb
  db/migrate/20211207131716_add_index_on_total_score_to_validator_score_v1.rb
  db/schema.rb
Labels: ready to review

#296 179907326_fix_methods_in_solana_rpc_client
  app/services/solana_rpc_client.rb
Labels: ready to review

#297 180699160 add dao to homepage
  app/assets/images/daopool.png
  app/assets/images/jpool.png
  app/assets/images/lido.png
  app/assets/stylesheets/application.scss
  app/assets/stylesheets/carousels.scss
  app/helpers/validators_helper.rb
  app/views/validators/_banner.html.erb
Labels: ready to review

#300 180674513_add_stop_warning
  app/models/validator.rb
  app/models/validator_score_v1.rb
  app/views/public/faq.en.html.erb
  app/views/validators/_table.html.erb
  app/views/validators/show.html.erb
  db/migrate/20211227132812_add_admin_warning_to_validators.rb
  db/schema.rb
  test/models/validator_score_v1_test.rb
Labels: ready to review
