Repository brianlong/www.validators.app, pull requests merged in 2021-07, with the labels that each got.

#140 178772761_fix_test_suite
  test/workers/validator_check_active_worker_test.rb
Labels: ready to merge

#138 178765875_add_pagination_to_endpoint
  app/controllers/api/v1/api_controller.rb
  test/controllers/api/v1/api_controller_test.rb
Labels: ready to merge

#141 178765879_add_search_feature_to_api
  app/controllers/api/v1/api_controller.rb
  test/controllers/api/v1/api_controller_test.rb
Labels: ready to merge

#137 178718094-api-access-using-origin
  Gemfile
  Gemfile.lock
  app/controllers/api/v1/base_controller.rb
  config/credentials.yml.enc
  config/credentials/stage.yml.enc
  config/credentials/test.yml.enc
  config/initializers/cors.rb
  test/controllers/api/v1/api_controller_test.rb
Labels: ready to merge

#139 178558379 reactivate nodes
  app/models/validator.rb
  app/services/validator_check_active_service.rb
  app/workers/validator_check_active_worker.rb
  test/services/validator_check_active_service_test.rb
  test/workers/validator_check_active_worker_test.rb
Labels: ready to merge

#142 fix software version algorithm
  app/helpers/validators_helper.rb
  app/logic/validator_score_v1_logic.rb
  app/views/validators/_software_versions.html.erb
  test/logic/validator_score_v1_logic_test.rb
Labels: ready to review

#144 178798724_update_api_docs
  app/views/public/api_documentation.html.erb
Labels: ready to review

#148 178799698 add commission report view
  app/controllers/public_controller.rb
  app/models/commission_history.rb
  app/services/create_commission_history_service.rb
  app/views/layouts/_footer.html.erb
  app/views/public/_commission_changed_indicator.html.erb
  app/views/public/commission_histories.html.erb
  app/views/validators/show.html.erb
  config/routes.rb
  db/migrate/20210708133030_add_network_to_commission_histories.rb
  db/schema.rb
  test/factories/commission_histories.rb
Labels: ready to merge

#145 178792573-commission-change-report
  app/controllers/public_controller.rb
  app/models/batch.rb
  app/models/commission_history.rb
  app/models/validator.rb
  app/models/validator_score_v1.rb
  app/services/create_commission_history_service.rb
  app/views/layouts/_footer.html.erb
  app/views/public/_commission_changed_indicator.html.erb
  app/views/public/commission_histories.html.erb
  app/views/validators/show.html.erb
  config/routes.rb
  db/migrate/20210708073955_create_commission_histories.rb
  db/migrate/20210708133030_add_network_to_commission_histories.rb
  db/migrate/20210708140201_add_epoch_info_to_commission_history.rb
  db/migrate/20210709093055_add_index_on_network_to_batches.rb
  db/schema.rb
  test/factories/commission_histories.rb
  test/models/commission_history_test.rb
  test/models/validator_history_test.rb
  test/models/validator_score_v1_test.rb
  test/services/create_commission_history_service_test.rb
Labels: ready to merge

#153 178799307 fix software_version sorting
  app/helpers/validators_helper.rb
Labels: ready to merge

#149 178811031 old commission changes
  script/back_fill_commission_history.rb
  test/models/validator_history_test.rb
  test/scripts/back_fill_commission_history_script_test.rb
Labels: ready to merge

#155 178861372 current data in detail page
  app/assets/stylesheets/tables.scss
  app/assets/stylesheets/variables.scss
  app/controllers/public_controller.rb
  app/controllers/validators_controller.rb
  app/queries/validator_block_history_query.rb
  app/views/validators/_block_history_chart.html.erb
  app/views/validators/_spark_line_chart.html.erb
  app/views/validators/_spark_line_vote.html.erb
  app/views/validators/index.html.erb
  app/views/validators/show.html.erb
  config/initializers/colors.rb
  doc/color_pallette.txt
Labels: ready to merge

#158 178881010 filter by software version
  app/controllers/public_controller.rb
  app/queries/validator_search_query.rb
  app/views/validators/_software_versions.html.erb
  test/queries/validator_search_query_test.rb
Labels: ready to merge

#160 178913633-deduplicate-vote-accounts
  app/logic/solana_logic.rb
  dev/solana_pipeline_demo.rb
Labels: ready to merge

#154 178877158_test_gem
  Gemfile
  Gemfile.lock
  app/logic/solana_logic.rb
  app/services/solana_rpc_client.rb
  config/cluster.yml.example
  config/credentials/stage.yml.enc
  config/initializers/solana_rpc_ruby.rb
  test/logic/solana_logic_test.rb
  test/vcr_cassettes/solana_client_request.yml
  test/vcr_cassettes/solana_client_request_incorrect_cluster.yml
Labels: on staging

#150 178551916 cluster stats frontend
  app/assets/stylesheets/application.scss
  app/assets/stylesheets/tables.scss
  app/assets/stylesheets/tabs.scss
  app/assets/stylesheets/typography.scss
  app/controllers/cluster_stats_controller.rb
  app/queries/validator_block_history_query.rb
  app/queries/validator_score_query.rb
  app/queries/vote_account_history_query.rb
  app/views/cluster_stats/index.html.erb
  app/views/layouts/_footer.html.erb
  app/views/validators/_software_versions.html.erb
  app/views/validators/_sort_bar.erb
  app/views/validators/_speedometer_chart.html.erb
  app/views/validators/index.html.erb
  config/initializers/colors.rb
  config/routes.rb
  test/controllers/cluster_stats_controller_test.rb
  test/queries/validator_block_history_query_test.rb
  test/queries/validator_score_query_test.rb
  test/queries/vote_account_history_query_test.rb
Labels: ready to review

#163 178962732_select_only_needed_fields_in_api_query
  app/controllers/api/v1/api_controller.rb
Labels: ready to merge

#164 178962742_eager_load_vote_accounts
  app/controllers/api/v1/api_controller.rb
  app/queries/validator_search_query.rb
Labels: ready to merge

#161 178910745_fix_displayed_validator_software_version
  app/logic/report_logic.rb
  app/views/validators/show.html.erb
  test/logic/report_logic_test.rb
Labels: ready to merge

#166 178971561_add_select_with_fields_specified_to_validators_show
  app/controllers/api/v1/api_controller.rb
Labels: ready to review

#168 178910745_fix_displayed_validator_software_version_fix
  app/logic/report_logic.rb
  app/views/validators/show.html.erb
  test/logic/report_logic_test.rb
Labels: ready to merge

#169 178962750_deal_with_ip
  app/controllers/api/v1/api_controller.rb
  app/models/ip.rb
  app/models/validator_score_v1.rb
  app/views/api/v1/validators/_validator.json.jbuilder
  test/models/ip_test.rb
  test/models/validator_score_v1_test.rb
Labels: ready to merge

#173 179000784_re_fix_action_view_template_error
  app/logic/report_logic.rb
  test/helpers/validators_helper_test.rb
  test/logic/report_logic_test.rb
Labels: ready to merge

#172 179000241-re-fix-charts
  app/logic/solana_logic.rb
  app/models/vote_account_history.rb
  dev/solana_pipeline_demo.rb
Labels: ready to merge

#171 178985735_switch_from_using_partial_in_api
  app/controllers/api/v1/api_controller.rb
  app/models/batch.rb
  app/models/ip.rb
  app/models/validator.rb
  app/models/validator_score_v1.rb
  app/models/vote_account.rb
  app/views/api/v1/validators/_validator.json.jbuilder
  app/views/api/v1/validators/index.json.jbuilder
  config/environments/development.rb
  config/environments/production.rb
  config/environments/stage.rb
  config/environments/test.rb
  test/controllers/contact_request_controller_test.rb
  test/models/validator_test.rb
Labels: ready to merge

#174 179034755_fix_software_version_table
  app/controllers/public_controller.rb
  app/logic/report_logic.rb
  test/controllers/public_controller_test.rb
  test/logic/report_logic_test.rb
Labels: ready to review

#177 178912445-fix-software-version-score
  app/logic/validator_score_v1_logic.rb
  app/models/validator_score_v1.rb
  app/services/validator_software_version.rb
  test/models/validator_score_v1_test.rb
Labels: ready to merge
