Repository brianlong/www.validators.app, pull requests merged in 2021-09, with the labels that each got.

#204 179268304_filter_results_in_commission_changes_table
  app/assets/stylesheets/pagination.scss
  app/javascript/packs/commission_histories/commission_history_row.js
  app/javascript/packs/commission_histories/index.js
  app/javascript/packs/commission_histories/index_template.vue
Labels: ready to merge

#202 179359356_add_current_epoch
  app/controllers/api/v1/api_controller.rb
  app/models/epoch_history.rb
  test/controllers/api/v1/api_controller_test.rb
Labels: ready to review

#210 179359356_add_network_to_current_epoch
  app/controllers/api/v1/api_controller.rb
Labels: ready to review

#205 179040897_move_stats_from_homepage_to_cluster_stats_view
  app/assets/stylesheets/footer.scss
  app/controllers/cluster_stats_controller.rb
  app/views/cluster_stats/_stats.html.erb
  app/views/cluster_stats/index.html.erb
  app/views/layouts/_footer.html.erb
  app/views/validators/index.html.erb
Labels: WIP

#214 179657491_add_more_descriptive_hint_to_search
  app/views/validators/_search_bar.html.erb
Labels: ready to review

#213 179657492_change_count_in_software_version_report_to_sth_more_meaningful
  app/views/validators/_software_versions.html.erb
Labels: ready to review

#220 179657493 change behaviour of network links
  app/controllers/application_controller.rb
  app/javascript/packs/navigation/network_buttons.js
  app/javascript/packs/navigation/network_buttons_template.vue
  app/views/layouts/_header.html.erb
  package.json
  yarn.lock
Labels: ready to merge

#216 179657490_more_descriptive_pop_ups_hints
  app/assets/stylesheets/tables.scss
  app/javascript/packs/application.js
  app/views/cluster_stats/index.html.erb
  app/views/data_centers/_asn_head.html.erb
  app/views/data_centers/_data_center_head.html.erb
  app/views/validators/index.html.erb
  config/locales/en.yml
Labels: ready to merge

#221 179740168_add_lido_and_socean
  app/views/validators/_banner.html.erb
Labels: ready to merge
