Repository brianlong/www.validators.app, pull requests merged in 2021-05, with the labels that each got.

#84 177711219_change_schedule_for_stage
  config/schedule.rb
Labels: ready to review

#87 178014329 private node zero points
  app/assets/stylesheets/application.scss
  app/assets/stylesheets/images.scss
  app/assets/stylesheets/tables.scss
  app/helpers/application_helper.rb
  app/models/validator.rb
  app/models/validator_score_v1.rb
  app/views/validators/_scores.html.erb
  app/views/validators/index.html.erb
  app/views/validators/show.html.erb
  db/schema.rb
  script/validators_get_info.rb
  test/models/validator_score_v1_test.rb
  test/models/validator_test.rb
Labels: ready to merge

#97 178128406_update_test_key
  config/credentials/test.yml.enc
  config/credentials/test_key.gpg
Labels: ready to merge

#95 178085179 hide commission for private validators
  app/views/validators/index.html.erb
Labels: ready to review

#96 178085324 fix skipped vote
  app/models/vote_account.rb
  app/views/validators/index.html.erb
Labels: ready to review

#93 178085174_support_enhanced_characters
  app/logic/solana_logic.rb
  app/models/contact_request.rb
  app/models/epoch_history.rb
  app/models/ip.rb
  app/models/ping_time.rb
  app/models/ping_time_stat.rb
  app/models/report.rb
  app/models/user.rb
  app/models/validator.rb
  app/models/validator_history.rb
  config/database.example.yml
  config/initializers/ar_innodb_row_format.rb
  config/initializers/core_ext.rb
  db/migrate/20210514111517_change_encoding_to_utfmb4.rb
  db/schema.rb
  lib/core_ext/string.rb
  test/lib/core_ext/string_test.rb
  test/models/validator_test.rb
Labels: on staging

#103 178177826_update_schema_rb
  app/models/batch.rb
  app/models/collector.rb
  app/models/contact_request.rb
  app/models/epoch_history.rb
  app/models/ip.rb
  app/models/ip_override.rb
  app/models/ping_time.rb
  app/models/ping_time_stat.rb
  app/models/report.rb
  app/models/user.rb
  app/models/validator.rb
  app/models/validator_block_history.rb
  app/models/validator_block_history_stat.rb
  app/models/validator_history.rb
  app/models/validator_ip.rb
  app/models/validator_score_v1.rb
  app/models/vote_account.rb
  app/models/vote_account_history.rb
  db/schema.rb
Labels: ready to review

#72 177618304 epoch wall clock
  app/controllers/api/v1/epochs_controller.rb
  app/logic/solana_logic.rb
  app/models/epoch_wall_clock.rb
  app/views/api/v1/epochs/_epoch_wall_clock.json.jbuilder
  app/views/api/v1/epochs/index.json.jbuilder
  app/views/public/api_documentation.html.erb
  config/routes.rb
  db/migrate/20210407114051_create_epoch_wall_clocks.rb
  db/migrate/20210413052956_add_ending_slot_to_epoch_wall_clock.rb
  db/schema.rb
  test/controllers/api/v1/api_controller_test.rb
  test/controllers/api/v1/epochs_controller_test.rb
  test/factories/epoch_wall_clocks.rb
  test/logic/solana_logic_test.rb
  test/models/epoch_wall_clock_test.rb
  test/support/response_helper.rb
  test/test_helper.rb
Labels: ready to merge

#107 177581555 create chart in skipped vote column
  app/assets/stylesheets/log_deep_dive.scss
  app/assets/stylesheets/tables.scss
  app/controllers/public_controller.rb
  app/helpers/validators_helper.rb
  app/views/layouts/application.html.erb
  app/views/validators/_banner.html.erb
  app/views/validators/_block_history_chart.html.erb
  app/views/validators/_spark_line_block.html.erb
  app/views/validators/_spark_line_block_distance.html.erb
  app/views/validators/_spark_line_skipped_slots.html.erb
  app/views/validators/_spark_line_skipped_vote.html.erb
  app/views/validators/_spark_line_vote.html.erb
  app/views/validators/_spark_line_vote_distance.html.erb
  app/views/validators/index.html.erb
Labels: ready to review

#106 177492288 report by asn
  app/controllers/api/v1/api_controller.rb
  app/controllers/asns_controller.rb
  app/controllers/data_centers_controller.rb
  app/helpers/data_centers_helper.rb
  app/helpers/validators_helper.rb
  app/models/validator_score_v1.rb
  app/services/sorted_data_centers.rb
  app/views/api/v1/validators/_validator.json.jbuilder
  app/views/asns/show.html.erb
  app/views/data_centers/_asn_head.html.erb
  app/views/data_centers/_asn_list.html.erb
  app/views/data_centers/_data_center_head.html.erb
  app/views/data_centers/_data_center_list.html.erb
  app/views/data_centers/data_center.html.erb
  app/views/data_centers/index.html.erb
  app/views/public/api_documentation.html.erb
  app/views/validators/_as_row.html.erb
  app/views/validators/_basic_list.html.erb
  config/routes.rb
  test/controllers/asns_controller_test.rb
  test/factories/ips.rb
  test/models/validator_score_v1_test.rb
  test/services/sorted_data_centers_test.rb
Labels: ready to merge
