Repository brianlong/www.validators.app, pull requests merged in 2022-10, with the labels that each got.

#570 183370357 fix chart annotations
  app/assets/stylesheets/tables.scss
  app/helpers/validators_helper.rb
  app/javascript/packs/stake_accounts/charts/root_distance_chart.js
  app/javascript/packs/stake_accounts/charts/skipped_slot_chart.js
  app/javascript/packs/stake_accounts/charts/skipped_vote_speedometer.js
  app/javascript/packs/stake_accounts/charts/vote_distance_chart.js
  app/javascript/packs/stake_accounts/stake_account_row.js
  app/javascript/packs/stake_accounts/validator_row.js
  app/views/validators/_table.html.erb
Labels: ready to review

#573 183274925_add_letter_opener
  config/environments/development.rb
  config/routes.rb
  test/mailers/previews/commission_history_mailer_preview.rb
Labels: ready to review

#569 183379638_use_validator_ip_active_on_gossip_nodes
  app/logic/gossip_node_logic.rb
  app/models/data_center_host.rb
  app/models/gossip_node.rb
  test/models/data_center_host_test.rb
  test/models/data_center_test.rb
  test/models/gossip_node_test.rb
Labels: ready to review

#576 183402909- Add web3 solana package; fix browserlist config
  .browserslistrc
  package.json
  yarn.lock
Labels: ready to review

#589 183531771 - fix circulating supply delay
  app/javascript/packs/validators/circulating_supply.vue
Labels: ready to review

#583 183466948 update data center stats
  app/controllers/api/v1/data_centers_controller.rb
  app/javascript/packs/validators/validators_map.vue
  app/javascript/packs/validators/validators_map_data_center_details.js
  app/models/data_center_stat.rb
  app/services/data_centers/fill_data_center_stats.rb
  db/migrate/20221011131406_add_active_validators_count_to_data_center_stats.rb
  db/schema.rb
  test/controllers/api/v1/data_centers_controller_test.rb
  test/factories/data_center_stats.rb
  test/services/data_centers/fill_data_center_stats_test.rb
Labels: ready to review

#591 183532155 - add front_stats_update to capistrano deploy config
  config/deploy.rb
Labels: ready to review

#593 Bump Vuex to 3.6.2
  package.json
  yarn.lock
Labels: ready to merge

#594 183522592 - add testnet stats for homepage
  app/javascript/packs/stores/main_store.js
  app/views/validators/_ping_stats_banner.html.erb
Labels: ready to merge

#603 183580511 update new homepage layout
  app/assets/stylesheets/map.scss
  app/javascript/packs/validators/validators_map_data_center_details.js
  app/views/validators/home_new.html.erb
Labels: invalid

#601 183590725 - add stake worker to testnet
  app/javascript/packs/validators/circulating_supply.vue
  daemons/validator_score_testnet_v1_daemon.rb
Labels: ready to review

#604 183567669 - fix missing method error; daemon minor improvements
  app/logic/agent_logic.rb
  script/validators_update_avatar_url.rb
Labels: ready to review

#602 183591385 - fix missing testnet leader and validators map
  app/javascript/packs/leaders/leaders_stats_component.js
  app/javascript/packs/leaders/leaders_stats_component_template.vue
  app/javascript/packs/validators/validators_map.js
  app/javascript/packs/validators/validators_map.vue
Labels: ready to review

#596 183383678 Search for ping things
  app/controllers/api/v1/ping_things_controller.rb
  app/javascript/packs/ping_thing/index_template.vue
  app/javascript/packs/ping_thing/ping_thing_table.vue
  test/controllers/api/v1/ping_things_controller_test.rb
Labels: ready to merge

#608 183607579 - move distance and skipped components to the homepage
  app/javascript/packs/distance_stats/distance_stats_component.js
  app/javascript/packs/distance_stats/distance_stats_component_template.vue
  app/javascript/packs/skipped_stats/skipped_stats_component.js
  app/javascript/packs/skipped_stats/skipped_stats_component_template.vue
  app/models/cluster_stat.rb
  app/services/create_cluster_stats_service.rb
  app/views/cluster_stats/_root_distance.html.erb
  app/views/cluster_stats/_skipped_slot.html.erb
  app/views/cluster_stats/_skipped_vote.html.erb
  app/views/cluster_stats/_vote_distance.html.erb
  app/views/cluster_stats/index.html.erb
  app/views/validators/home_new.html.erb
  app/workers/cluster_stats_worker.rb
  daemons/validator_score_mainnet_v1_daemon.rb
  daemons/validator_score_testnet_v1_daemon.rb
  db/migrate/20221024124535_add_distance_and_skipped_to_cluster_stat.rb
  db/schema.rb
  package.json
  test/factories/reports.rb
  test/services/create_cluster_stats_service_test.rb
  yarn.lock
Labels: ready to review

#611 183637326 - remove cluster stats model attrs from the report
  app/logic/report_logic.rb
  app/services/create_cluster_stats_service.rb
  test/controllers/cluster_stats_controller_test.rb
  test/services/create_cluster_stats_service_test.rb
Labels: ready to review

#606 183640495 fix error with duplicated keys for a map
  app/assets/stylesheets/map.scss
  app/controllers/api/v1/data_centers_controller.rb
Labels: ready to review

#613 183580265 add link to validator details
  app/javascript/packs/leaders/leaders_stats_component_template.vue
Labels: ready to review

#614 183640408 tweak homepage layout
  app/javascript/packs/clusters/cluster_numbers_component.js
  app/javascript/packs/clusters/cluster_numbers_component.vue
  app/javascript/packs/clusters/cluster_performance_stats_component.js
  app/javascript/packs/clusters/cluster_performance_stats_component_template.vue
  app/javascript/packs/distance_stats/distance_stats_component_template.vue
  app/javascript/packs/epochs/epoch_stats_component.js
  app/javascript/packs/epochs/epoch_stats_component_template.vue
  app/javascript/packs/leaders/leaders_stats_component_template.vue
  app/javascript/packs/navigations/network_buttons.js
  app/javascript/packs/navigations/network_buttons_template.vue
  app/javascript/packs/ping_things/bubble_chart.js
  app/javascript/packs/ping_things/index.js
  app/javascript/packs/ping_things/index_template.vue
  app/javascript/packs/ping_things/ping_thing_header.vue
  app/javascript/packs/ping_things/ping_thing_table.vue
  app/javascript/packs/ping_things/stats_bar.js
  app/javascript/packs/ping_things/stats_bar.vue
  app/javascript/packs/ping_things/stats_chart.js
  app/javascript/packs/skipped_stats/skipped_stats_component.js
  app/javascript/packs/skipped_stats/skipped_stats_component_template.vue
  app/views/layouts/_header.html.erb
  app/views/ping_things/index.html.erb
  app/views/validators/_ping_stats_banner.html.erb
  app/views/validators/home_new.html.erb
Labels: ready to review

#617 183639579 - reduce leader component intervals
  config/deploy.rb
  daemons/concerns/leader_stats_helper.rb
  daemons/front_stats_update_daemon.rb
  daemons/leader_stats_update.service
  daemons/leader_stats_update_daemon.rb
Labels: ready to review

#618 183651877 - uncomment leader stats update daemon during restart task
  config/deploy.rb
Labels: ready to review
