Repository brianlong/www.validators.app, pull requests merged in 2022-04, with the labels that each got.

#399 181583636_investigate_performance_on_show_page
  app/controllers/validators_controller.rb
Labels: ready to merge

#401 181570574_fix_failing_test
  app/controllers/api/v1/sol_prices_controller.rb
Labels: ready to review

#404 181727053_unify_routes
  config/routes.rb
Labels: ready to review

#395 181283540 Add pagination to ping things
  app/controllers/api/v1/ping_things_controller.rb
  app/javascript/packs/ping_thing/bubble_chart.js
  app/javascript/packs/ping_thing/index_template.vue
  app/javascript/packs/ping_thing/ping_thing_table.vue
  app/views/ping_things/_scatter_chart.html.erb
  test/controllers/api/v1/ping_thing_controller_test.rb
Labels: ready to review

#402 181570115_with_history_option
  app/controllers/api/v1/validators_controller.rb
  app/controllers/concerns/validators_controller_helper.rb
  app/models/validator_score_v1.rb
  test/controllers/api/v1/validators_controller_test.rb
Labels: ready to review

#405 181679704_use_maxmind_in_logic
  script/data_centers_scripts/append_data_centers_geo_data.rb
Labels: ready to review

#406 181791161_remove_not_used_script
  script/append_ip_geo_data.rb
  script/concerns/fix_data_center_module.rb
  script/concerns/fix_ip_module.rb
  script/data_centers_scripts/fix_data_centers_hetzner.rb
  script/data_centers_scripts/fix_data_centers_ovh.rb
  script/data_centers_scripts/fix_data_centers_webnx.rb
  script/fix_ip_hetzner.rb
  script/fix_ip_ovh.rb
  script/fix_ip_webnx.rb
Labels: ready to review

#403 181770137_fix_warning
  daemons/gather_rpc_mainnet_daemon.rb
  daemons/gather_rpc_testnet_daemon.rb
  dev/report_tower_height.rb
  script/gather_rpc_data.rb
  script/gather_rpc_data_mainnet.rb
  test/logic/report_logic_test.rb
Labels: ready to review

#411 181846395_investigate_slow_query_on_vote_account
  app/controllers/vote_accounts_controller.rb
  app/views/vote_accounts/_vote_account_histories_table.html.erb
Labels: ready to review

#413 181846381_fix_displayed_validator_identity
  app/controllers/vote_accounts_controller.rb
  app/views/validators/show.html.erb
  config/routes.rb
  test/controllers/vote_accounts_controller_test.rb
Labels: ready to review

#408 181583347_unify_query_for_list_and_single_validator
  app/controllers/api/v1/validators_controller.rb
  app/queries/validator_query.rb
  test/queries/validator_query_test.rb
Labels: ready to review

#409 181820023_remove_unused_scripts
  config/schedule.rb
  dev/create_home_page_chart.rb
  script/gather_rpc_data.rb
  script/gather_rpc_data_mainnet.rb
  script/legacy/fix_ip_marbis.txt
  script/legacy/fix_misc_ip.sql
  script/one_time_scripts/archive_for_restart.rb
  script/one_time_scripts/back_fill_commission_history.rb
  script/one_time_scripts/back_fill_epoch_data.rb
  script/one_time_scripts/back_fill_validator_histories.rb
  script/one_time_scripts/copy_data_to_data_centers.rb
  script/one_time_scripts/fill_skipped_slot_all_average_in_batches.rb
  script/one_time_scripts/reduce_validators_with_invalid_config.rb
  script/one_time_scripts/write_validator_block_history_stats.rb
  script/one_time_scripts/write_validator_histories.rb
  script/one_time_scripts/write_validator_histories_all.rb
  script/one_time_scripts/write_validator_score_v1s.rb
  test/scripts/back_fill_commission_history_script_test.rb
Labels: ready to review

#412 181309973 ping thing stats
  app/assets/stylesheets/buttons.scss
  app/assets/stylesheets/header.scss
  app/controllers/api/v1/ping_thing_stats_controller.rb
  app/javascript/packs/ping_thing/bubble_chart.js
  app/javascript/packs/ping_thing/index_template.vue
  app/javascript/packs/ping_thing/stats_chart.js
  app/javascript/src/sol_prices_charts.js
  app/models/collector.rb
  app/models/commission_history.rb
  app/models/ping_thing.rb
  app/models/ping_thing_stat.rb
  app/services/create_ping_thing_stats_service.rb
  app/views/validators/_search_bar.html.erb
  app/workers/ping_thing_stats_worker.rb
  config/routes.rb
  config/schedule.rb
  db/migrate/20220405100027_create_ping_thing_stats.rb
  db/schema.rb
  dev/create_test_ping_things.rb
  script/one_time_scripts/back_fill_ping_thing_stats.rb
  test/factories/ping_thing_stats.rb
  test/models/ping_thing_stat_test.rb
  test/models/ping_thing_test.rb
  test/services/create_ping_thing_stats_service_test.rb
Labels: ready to review

#424 181958427_fix_conditions
  app/services/validator_check_active_service.rb
  test/services/validator_check_active_service_test.rb
Labels: ready to review, ready to merge

#423 181886696_add_ping_thing_stats_to_api
  app/controllers/api/v1/ping_thing_stats_controller.rb
  app/models/ping_thing_stat.rb
  app/services/create_ping_thing_stats_service.rb
  app/views/public/api_documentation.html.erb
  test/controllers/api/v1/ping_thing_stats_controller_test.rb
  test/controllers/api/v1/ping_things_controller_test.rb
  test/models/ping_thing_stat_test.rb
  test/services/create_ping_thing_stats_service_test.rb
Labels: ready to review

#425 181967839_update_gh_actions
  .github/workflows/pronto.yml
  .github/workflows/test_suite.yml
Labels: ready to review

#427 181922327 add consensus mods scores
  app/javascript/packs/stake_accounts/validator_row.js
  app/models/validator.rb
  app/models/validator_score_v1.rb
  app/views/public/api_documentation.html.erb
  app/views/public/faq.en.html.erb
  app/views/validators/_scores.html.erb
  db/migrate/20220426110336_add_consensus_mods_score_to_validator_score_v1.rb
  db/migrate/20220426111323_add_consensus_mods_to_validator.rb
  db/schema.rb
  test/controllers/api/v1/validators_controller_test.rb
  test/factories/validator_score_v1s.rb
  test/factories/validators.rb
  test/models/validator_score_v1_test.rb
Labels: ready to review
