Repository brianlong/www.validators.app, pull requests merged in 2022-09, with the labels that each got.

#545 183114541 endpoint for a map
  app/controllers/api/v1/data_centers_controller.rb
  app/models/data_center.rb
  app/models/data_center_host.rb
  app/models/data_center_stat.rb
  app/services/data_centers/fill_data_center_stats.rb
  app/workers/data_center_stats_worker.rb
  config/routes.rb
  config/schedule.rb
  db/migrate/20220902070039_create_data_center_stats.rb
  db/migrate/20220905064408_add_index_on_network_and_data_centers_id_to_dc_stats.rb
  db/schema.rb
  test/controllers/api/v1/data_centers_controller_test.rb
  test/factories/data_center_stats.rb
  test/models/data_center_host_test.rb
  test/models/data_center_stat_test.rb
  test/models/data_center_test.rb
  test/services/data_centers/fill_data_center_stats_test.rb
Labels: ready to merge

#554 183298708 add slot latency to pt stats
  app/javascript/packs/ping_thing/stats_chart.js
  app/models/ping_thing_stat.rb
  app/services/create_ping_thing_stats_service.rb
  db/migrate/20220919072658_add_slot_latency_to_ping_thing_stats.rb
  db/schema.rb
  dev/create_test_ping_things.rb
  test/services/create_ping_thing_stats_service_test.rb
Labels: ready to merge

#560 183341305_add_validator_ip_activeTo_gossip_nodes
  app/models/gossip_node.rb
  test/models/gossip_node_test.rb
Labels: ready to review

#563 183341356_remove_duplicated_inactive_validator_ips
  app/services/validator_ips/remove_duplicated_inactive_validator_ips.rb
  script/validator_ips/remove_duplicated_inactive_validator_ips.rb
Labels: WIP, ready to review

#561 183323571_remove_validators_ips_without_val_or_gossip_node_assigned
  script/validator_ips/remove_without_validator_or_gossip_node.rb
Labels: ready to review

#568 183390859_create_active_validator_ips_for_gossip_nodes
  app/models/gossip_node.rb
  test/models/gossip_node_test.rb
Labels: ready to review
