Repository brianlong/www.validators.app, pull requests merged in 2023-03, with the labels that each got.

#735 184544114 - add trent-mode page
  app/assets/stylesheets/forms.scss
  app/assets/stylesheets/pagination.scss
  app/controllers/concerns/validators_controller_helper.rb
  app/controllers/validators_controller.rb
  app/helpers/validators_helper.rb
  app/views/layouts/application.html.erb
  app/views/validators/_no_search_results.html.erb
  app/views/validators/_search_bar.html.erb
  app/views/validators/_sort_bar.erb
  app/views/validators/_toggle_bar.html.erb
  app/views/validators/index.html.erb
  app/views/validators/trent_mode.html.erb
  config/locales/pl.yml
  config/routes.rb
  test/controllers/validators_controller_test.rb
Labels: ready to merge

#748 184655857 - Enable wildcard search for validator name
  app/queries/validator_search_query.rb
  test/queries/validator_search_query_test.rb
Labels: ready to review

#751 184673043 - Update search filed placeholder
  app/javascript/packs/navigations/validator_searcher_bar_template.vue
  app/views/validators/_search_bar.html.erb
Labels: ready to review

#730 184383182 api limit rack attack
  Gemfile
  Gemfile.lock
  app/views/public/api_documentation.html.erb
  config/credentials.yml.enc
  config/credentials/production.yml.enc
  config/credentials/stage.yml.enc
  config/environments/development.rb
  config/environments/production.rb
  config/initializers/rack_attack.rb
Labels: ready to review

#745 181957663 update chartjs
  app/assets/stylesheets/tables.scss
  app/helpers/application_helper.rb
  app/javascript/packs/ping_things/bubble_chart.js
  app/javascript/packs/ping_things/index_template.vue
  app/javascript/packs/ping_things/ping_thing_table.vue
  app/javascript/packs/ping_things/stats_bar.vue
  app/javascript/packs/ping_things/stats_chart.js
  app/javascript/packs/stake_accounts/charts/chart_variables.js
  app/javascript/packs/stake_accounts/charts/root_distance_chart.js
  app/javascript/packs/stake_accounts/charts/skipped_slot_chart.js
  app/javascript/packs/stake_accounts/charts/skipped_vote_speedometer.js
  app/javascript/packs/stake_accounts/charts/vote_distance_chart.js
  app/javascript/packs/stake_accounts/index.js
  app/javascript/packs/validators/charts/block_history_chart.js
  app/javascript/packs/validators/charts/chart_variables.js
  app/javascript/packs/validators/charts/root_distance_chart.js
  app/javascript/packs/validators/charts/skipped_slots_large_chart.js
  app/javascript/packs/validators/charts/skipped_slots_small_chart.js
  app/javascript/packs/validators/charts/skipped_vote_speedometer.js
  app/javascript/packs/validators/charts/vote_distance_chart.js
  app/javascript/packs/validators/charts/vote_history_chart.js
  app/javascript/packs/validators/components/scores.js
  app/javascript/packs/validators/components/validator_score_modal.vue
  app/javascript/packs/validators/validator_details.vue
  app/javascript/packs/validators/validator_row.js
  app/javascript/src/sol_prices_charts.js
  app/views/data_centers/_asn_list.html.erb
  app/views/layouts/application.html.erb
  app/views/validators/_skipped_slots_large_chart.html.erb
  app/views/validators/_spark_line_block_distance.html.erb
  app/views/validators/_spark_line_skipped_slots.html.erb
  app/views/validators/_spark_line_skipped_vote.html.erb
  app/views/validators/_spark_line_vote_distance.html.erb
  app/views/validators/_speedometer_chart.html.erb
  app/views/validators/_table.html.erb
  app/views/validators/_validator_large_chart.html.erb
  app/views/validators/_validator_skipped_slots_chart.html.erb
  app/views/validators/_validator_small_chart.html.erb
  config/initializers/colors.rb
  package.json
  yarn.lock
Labels: ready to merge

#757 184723973 handle no method error
  config/initializers/rack_attack.rb
Labels: ready to review

#728 184324000 - add switcher for stake accounts
  app/controllers/api/v1/stake_accounts_controller.rb
  app/javascript/packs/stake_accounts/index_template.vue
  app/javascript/packs/stake_accounts/stake_account_row.js
  app/javascript/packs/validators/validators_map.vue
  app/queries/stake_account_query.rb
Labels: ready to review

#755 184604151 - upgrade to 1.3.0 solanaRpcRuby
  Gemfile.lock
Labels: ready to review

#760 184689406 - add the environment to script
  script/remove_unconfirmed_users.rb
Labels: ready to review

#761 184694688 - fix private validator names
  app/helpers/application_helper.rb
  app/helpers/validators_helper.rb
  app/javascript/packs/validators/validator_row.js
  app/views/validators/_table.html.erb
  test/factories/validators.rb
  test/helpers/validators_helper_test.rb
Labels: ready to review

#557 Bump rails to version 6.1.7
  Gemfile.lock
  README.md
  config/sidekiq.yml.example
  package.json
  yarn.lock
Labels: WIP

#767 184810886-fix-coingecko-broadcast
  app/api_clients/coin_gecko_client.rb
  daemons/front_stats_update_daemon.rb
Labels: ready to merge

#765 184781969 sort versions by stake
  app/helpers/validators_helper.rb
  test/helpers/validators_helper_test.rb
Labels: ready to merge

#768 184689543-remove-users-without-log_in
  script/remove_unconfirmed_users.rb
  test/factories/user.rb
  test/scripts/remove_unconfirmed_users_test.rb
Labels: ready to review

#770 184529687 - upgrade version of solana rpc ruby gem
  Gemfile.lock
Labels: ready to review
